language: r
sudo: false
cache: packages
env:
  global:
  - secure: "FjhhU453R1gejDuL2jNeZQsY7y5T2qk/NER3NoFLw3P9dmjSt+3PWnubCGrg5nXbtyk6knv3nDrJraxdoSaagVkdeV92vMypgaDyoCmUqZMx4pHq7qDqzbL7M9zDHiHKntSwTP5+31g2DnW6KNn8Z0yaQ8xJ5A22J5ZoanYnxxbZjkR5YPVmDvxPW1rpY/o7nUPUAKmpfD7SX1gVuPzlNTBRiU6Me89U+CE8bXo5GpfanT/sY/SXEKG2AkTYuzGc9bUwNcpOyDlpMV9lO/885No2w3aVHHbYM76TZmTXkNlPCLEww6w8XKhcutcDa3avkPS7OgRg9PC3HWHiQ1zStTFEoqv/hc9LoZUZD2P8t0VnTOwGnezzICE89UqXyzlmVskEL50ovrEe/3M0W0EcSktTZT84bO9AgLEBRsUWoYxuLkalSFTJbtsjPMYla5cRxf53EyNRGGdypqMgpc9bmU85lbnoL0yWOt/WnNqgvTgE+40eliVKeQnmrZE23lGY9+FjHoRamaWISD64kzx0zrJg3SV1lP+dmjFqpanDMXognYJb/CK0oHgafwsSan0FpKGnN40BPxV0LLDrHHLoX2IM8XzAMh6WBglNbKKcfr9hA3M856osc3RdvblEFVuJaNmO5Uxm+xUr+wvMfIfTfIAGeuqJPyPADD9cToFoMtk="
r_github_packages:
- rstudio/rmarkdown
install:
- R -e "install.packages('devtools')"
- R -e "devtools::install_github('rstudio/rmarkdown')"
- wget https://github.com/mathjax/MathJax/archive/master.zip
- unzip master.zip >/dev/null
- rm master.zip
- export RMARKDOWN_MATHJAX_PATH=$PWD/MathJax-master
- tools/deploy.sh start
script:
- R -e "rmarkdown::render_site('TCLB')"
after_success:
- tools/deploy.sh finish
