---
title: "about"
author: "Paweł Obrępalski"
date: "July 4, 2017"
output: html_document
---

Information about TCLB, beautiful pictures showing what can be done with it.

TCLB is a MPI+CUDA or MPI+CPU high-performance CFD simulation code, based on Lattice Boltzmann Method. It provides a clear interface for calculation of complex physics, and implementing new models.

##Authors

Author: [Łukasz Łaniewski-Wołłk](https://github.com/llaniewski)

Co-authors:
* [Michał Dzikowski](https://github.com/mdzik)

Contributors:
* [Wojtek Regulski](https://github.com/wojtasMEiL)
* [Zbigniew Gawłowicz](https://github.com/zgawlowicz)
* [Mariusz Rutkowski](https://github.com/mrutkowski-aero)
* [Dmytro Sashko](https://github.com/shkodm)

Developed at: [C-CFD Group](https://c-cfd.meil.pw.edu.pl/) at [Warsaw University of Technology](http://pw.edu.pl/) from 2012.

##License

The software is free to use for non-commercial purposes.

Any usage should be acknowledged accordingly (at least with a reference to this repository). Anyone wanting to use this software in scientific publications should consult the author for the apropriate reference. Any commercial use should be consulted beforehend with the author. Any derived code (even if only for a specific model) should be acknowledged.

Most importantly: if the software proved to be useful for you, please inform the author!

Contact: llaniewski(monkey)meil.pw.edu.pl