theme = "hugo-now-ui"
baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "TCLB"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "public"
BrandTarget = "_self"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Download"
    url = "/download"
    pre = "<i class='now-ui-icons design_app'></i>"
    weight = 1
[[menu.main]]
    name = "Features"
    pre = "<i class='now-ui-icons ui-1_settings-gear-63'></i>"
    url = "/features"
    weight = 4
    identifier = "features"
[[menu.main]]
    name = "2D laminar flow"
    url = "/features/flow2d"
    weight = 1
    parent = "features"
[[menu.main]]
    name = "Multi-phase flow"
    url = "/features/multiphase"
    weight = 1
    parent = "features"
[[menu.main]]
    name = "Docs"
    pre = "<i class='now-ui-icons files_single-copy-04'></i>"
    url = "http://docs.tclb.io/"
    weight = 5
    identifier = "docs"
[[menu.main]]
    name = "Editor"
    pre = "<i class='now-ui-icons design-2_ruler-pencil'></i>"
    url = "/editor"
    weight = 10
    identifier = "editor"
    parent = "usermenu0"
[[menu.main]]
    name = "Blog"
    pre = "<i class='now-ui-icons ui-1_calendar-60'></i>"
    url = "/post"
    weight = 11
    identifier = "post"
[[menu.main]]
    name = "Tags"
    pre = "<i class='now-ui-icons shopping_tag-content'></i>"
    url = "/tags"
    weight = 2
    parent = "features"    
[[menu.main]]
    identifier = "usermenu0"
    name = "User"
    pre = "<i class='fa fa-cogs'></i>"
    url = ""
    weight = 20
    
[[menu.footer]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/cfd-go/tclb"
    weight = 1

[[menu.editor]]
    name = "Open"
    url = "javascript: tclb_editor_open();"
    pre = "<i class='now-ui-icons arrows-1_cloud-download-93'></i>"
    weight = 1
[[menu.editor]]
    name = "Save"
    url = "javascript: tclb_editor_save();"
    pre = "<i class='now-ui-icons arrows-1_cloud-upload-94'></i>"
    weight = 2


[params]
    background = "img/bg11.jpg"
    tint = "white"
    custom_css = ["css/highlight.min.css", "css/custom.css"]
    custom_js = ["https://unpkg.com/netlify-auth-providers", "https://unpkg.com/js-cookie", "https://unpkg.com/github-api/dist/GitHub.bundle.min.js", "/js/ed/editor.js"]

    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    BrandTarget = "_self"

    

