baseurl = "https://example.org/"
languageCode = "en-us"
title = "TCLB Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

math = true

[params]
	# General information
	author = "llaniewski"
	description = "TCLB Documentation"
	copyright = "Not yet known"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/CFD-GO/TCLB"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "llaniewski"
	email   = ""


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "TCLB"
	url    = "TCLB/"
	weight = 10


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
