---
title: "Analyzing results"
author: "Paweł Obrępalski"
date: "July 4, 2017"
output: html_document
---

Results of the calculations can be analyzed using [ParaView](https://www.paraview.org/), an open-source, multi-platform data analysis and visualization application. It can be easily installed by running 
```bash
sudo apt-get install paraview
```
Or, if you want to install newer version, it can be downloaded [here](https://www.paraview.org/download/).

Paraview can open most of the files generated by the TCLB solver(`.pvti`,`.csv`) or required to run calculations(`.stl`). 

File extension  | Comment
-------------   | ------------------------------------------------------------------------------------------
`.vti`          | VTK files generated by the `<VTK>` callback in `.xml` case files. Each solver thread creates its own `.vti` file when saving them. That's why (usually) you do not want to open files with this extension.
**`.pvti`**     | Files linking separate `.vti` files, opening them will allow navigation through whole domain/time.
`.csv`          | Log files generated by the `<Log>` callback in `.xml` case files. Containing all the values of Settings and Globals defined in `Dynamics.R` TODO:podlinkować
`.xml`          | Configuration files, containing `.xml` case file and information about code version/compilation settings.
`.stl`          | Geometry files.

##Displaying results


