---
title: "User Manual"
author: "Paweł Obrępalski"
date: "July 3, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Installation
##Downloading files
```bash
git clone https://github.com/CFD-GO/TCLB.git
cd TCLB
```
##Dependencies

In order to use TCLB solver, the following tools are needed:

* [R](https://www.r-project.org/)
* packages for R: [optparse](https://cran.r-project.org/package=optparse), [numbers](https://cran.r-project.org/package=numbers),  [template](https://github.com/llaniewski/rtemplate), [gvector](https://github.com/llaniewski/gvector),  [polyAlgebra](https://github.com/llaniewski/polyAlgebra)
* [nVidia CUDA](https://developer.nvidia.com/cuda-zone) (if you want to use GPU)
* [python](https://www.python.org/)
* [numpy](http://www.numpy.org/) (if you want to use the integrated python interpreter)
* [python](https://www.python.org/), [python](http://www.sympy.org/) 
* [rPython](https://cran.r-project.org/package=rPython) (if you want to develop a model using python in place or R)
* [MPI](https://en.wikipedia.org/wiki/Message_Passing_Interface) (e.g. [OpenMPI](http://www.open-mpi.org

Most of them can be installed using the script provided within the code(tools/install.sh):

```bash
sudo tools/install.sh cuda 6.5-14
sudo tools/install.sh r
sudo tools/install.sh openmpi
     tools/install.sh rdep
sudo tools/install.sh python-dev
     tools/install.sh rpython
```

##Compilation

After installing all required dependencies, the code is ready to be compiled. In order to do so:
```bash
make configure
./configure
make -j 10 d2q9
```
Notes: `-j 10` is used to speed up the compilation process, by running multiple threads. `d2q9` is the name of the model, this solver comes with multiple models(TODO:link), which can be compiled(and used) by substituting `d2q9` for desired model name(e.g. `d3q27`).

###Configuration options

Option                | Effect
-------------         | ---------------------------------------------------------
`--enable-graphics`   | Enables the (TODO:okno podglądu).
`--disable-double`    | Switches to single(float) precision.
`--disable-cuda`      | Disables CUDA, thus compiling the code for CPU.
`--with-nlopt`        | Compilation with NLopt library for optimization.
`--with-python`       | Compilation with enabled Python integration(TODO:do użycia w XML).
`--with-r`            | Compilation with enabled R integration(TODO:do użycia w XML).

#Usage
```bash
CLB/MODEL_NAME/main case_path
```
Where `MODEL_NAME` is the name of the desired model(e.g.`d2q9`) and `case_path` is the location of case file(.xml), relative to the TCLB folder.

For example, to run `karman.xml` case, located in subfolder `example\flow\2d`, using `d2q9` model:

```bash
CLB/d2q9/main example/flow/2d/karman.xml
```

###CPU-based usage

By default the code will run on GPU, which requires a NVIDIA GPU with CUDA support. In order to run it on CPU, the code must be compiled using `--disable-cuda` option. In order to run the calculations on CPU in parallel, one need to start calculations using `mpirun` option:

```bash
mpirun -np X CLB/MODEL_NAME/main case_path
```
Where `X` is number of threads that will be created. Usually max number of threads is equal to number of cores of a processor, with the exception of CPUs with multi-threading.

#Case configuration

All case properties(geometry,BCs,model settings, etc.) are specified within XML files. All of them have structure similiar to the example given below:

```xml
<?xml version="1.0"?>
<CLBConfig version="2.0" output="output/test">
        <Geometry nx="1024" ny="100">
                <MRT><Box/></MRT>
                <WVelocity name="Inlet"><Box nx="1"/></WVelocity>
                <EPressure><Box dx="-1"/></EPressure>
                <Wall mask = "ALL">
                        <Box ny="1"/>
                        <Box dy="-1"/>
                </Wall>
        </Geometry>
        <Model>
                <Params Velocity-Inlet="0.01"/>
                <Params nu="0.05"/>
        </Model>
        <Solve Iterations="5000"/>
        <VTK Iterations="50" what = "U,P"/>
        <Solve Iterations="1000"/>
</CLBConfig>
```
Element                                         | Functionality
-------------                                   | -----------------------------------------------
`<?xml version="1.0"?>`                         | Header required for all case files.
`<CLBConfig output="output/test">`              | All configuration settings must be contained within this element, additionally it is possible to specify deisred output path and/or filename prefix here. In example all files will be saved in `~TCLB/output` folder, with all the filenames begining with `test` prefix.
`<Geometry nx="1024" ny="100">`                 | Element containing all informations regarding geometry(domain size/shape, whats insinde domain). `nx="1024"" ny="100"` specifies a domain containing 1024 elements in x-direction and 100 in y-direction. TODO: specyfikacja nx,dx,fx etc.
`<MRT><Box/></MRT>`                             | `MRT` is 
`<WVelocity name="Inlet"><Box nx="1"/></WVelocity>`   |Creates velocity inlet at western side of the domain(TODO: Orientation), with width equal to 1 element and assignes it name `Inlet`(usefull for specifying zonal parameters later on).
`<EPressure><Box dx="-1"/></EPressure>`           | Creates pressure outlet at eastern side of the domain, with width equal to to 1 element.
`<Wall mask = "ALL">` <br> `<Box ny="1"/>` <br> `<Box dy="-1"/>` <br> `</Wall>`  | Creates `wall` elements. `mask="ALL"` tells us that all types(also from other groups) will be overwritten by `wall` element type, e.g the collision enabled in `<MRT><Box/></MRT>` will be disabled.
`</Geometry>`                                   | Closing tag for `<Geometry>` element.
`<Model>`                                       | Element containing all desired model settings(`Params`)
`<Params Velocity-Inlet="0.01"/>`               | Setting the value of `Velocity` parameter to 0.01 in `Inlet` element(specified in Geometry).
`<Params nu="0.05"/>`                           | Setting the value of `nu` parametere to 0.05.
`</Model>`                                      | Closing tag for `<Model>` element. The case is initialized after this tag.
`<Solve Iterations="5000"/>`                    | Runs 5000 iterations
`<VTK Iterations="50"/>`                        | Specifies that next `<Solve>` element will create an VTK output file every 50 iterations, saving there U and P quantities. By default everything is saved, creating rather large file for bigger cases.
`<Solve Iterations="1000"/>`                    | Runs 1000 iterations, creating VTK output every 50 iterations, as specified earlier.
`</CLBConfig>`                                  | Closing tag for <CLBConfig> element, finishing whole case file.

All case files start with `<?xml version="1.0"?>` header. 

The configuration must be in the `<CLBConfig>` element(`<CLBConfig/>` at start and `</CLBConfig>` at the end). In this element the output path and/or prefix can be specified. In example all files will be saved in `~TCLB/output` folder, with all the filenames begining with `test` prefix.

`<Geometry>` element contains the definition of the 

##Geometry definition 

It's easy to imagine how the geometry elements are defined, by thinking about it as "painting". Each geometry element must have 2 parameters "what are we painting with" and "where are we painting":
```xml
<Wall mask="ALL">
  <Box dx="4" nx="10" ny="30"/>
</Wall>
```

In this example "what" is `Wall` element and "where" is `<Box dx="4" nx="10" ny="30"/>`. Defining "where" can be done in multiple ways, using `nx`,`dx`,`fx` arguments(similarly for `y` and `z`). If not specified otherwise, the element will span for the whole domain(e.g. `<MRT><Box/></MRT>` enables `MRT` collision in the entire domain). 

```{R echo=FALSE}
mybox = function(dx=0,fx=n,n=20,m=5) {
  par(mar=c(0,0,0,0))
  plot(NA,xlim=c(0,n),ylim=c(-3,m),bty='n',axes=FALSE,asp=1)
  rect(dx,0,fx,m,col=8)
  segments(0,0:m,n,0:m)
  segments(0:n,0,0:n,m)
}
brace = function(x1,y1,x2,y2,len=1,text,...){
  a=c(1,2,3,48,50)    # set flexion point for spline
  b=c(0,.2,.28,.7,.8) # set depth for spline flexion point
  curve = spline(a, b, n = 50, method = "natural")$y / 0.8
  curve = c(curve,rev(curve))
  i = which.max(curve)
  curve = cbind(seq(0,1,len=length(curve)),curve,1)
  v = c(x2-x1,y2-y1)
  v = rbind(v,c(v[2],-v[1])/sqrt(sum(v**2))*len,c(x1,y1))
  v = curve %*% v
  lines(v,asp=1)
  text(v[i,1],v[i,2],labels = text,...)
}

px = 1
py = 0.3
```
```{R fig.width=px, fig.height=py,echo=FALSE}
mybox(dx=4)
brace(0,0,4,0,text="dx",adj=c(0.5,1),cex=0.5)
```
```<Box dx="4"/>```{.xml}

```{R fig.width=px, fig.height=py,echo=FALSE}
mybox(dx=20-4)
brace(20-4,0,20,0,text="-dx",adj=c(0.5,1),cex=0.5)
```
```<Box dx="-4"/>```{.xml}

```{R fig.width=px, fig.height=py,echo=FALSE}
mybox(dx=4,fx=4+10)
brace(4,0,4+10,0,text="nx",adj=c(0.5,1),cex=0.5)
brace(0,0,4,0,text="dx",adj=c(0.5,1),cex=0.5)
```
```<Box dx="4" nx="10"/>```{.xml}

```{R fig.width=px, fig.height=py,echo=FALSE}
mybox(dx=4,fx=10)
brace(0,0,10,0,text="fx",adj=c(0.5,1),cex=0.5)
```
```<Box dx="4" fx="10"/>```{.xml}

###Possible geometry primitives

`Box` Creates a box with corners defined by `nx`/`dx`/`fx` etc. parameters.

`Wedge` Creates a wedge within a `box`, additionally `direction` must be specified ("LowerRight","LowerLeft","UpperRight","UpperLeft") e.g: `<Wedge dx="4" fx="10" dy="1" ny="10" direction="LowerRight"/>`

`Sphere` Creates a sphere within a `box`, can have different dimensions in x/y/z.

##Callbacks
Callbacks allow us to perform actions during calculations e.g. saving quantities to a file. Each action can be done once `<Log/>` or every X iterations `<Log Iterations="X"/>`All the desired actions must be specified before `Solve` element. E.g. example below will result in running 500 iterations without any output and then running 100 iterations with VTK export each 10 iterations. 
```xml
<Solve Iterations="500"/>
<VTK Iterations="10" />
<Solve Iterations="100"/>
```


####Solve
`<Solve Iterations="X"/>` Runs X iterations

####Log
`<Log Iterations="X"/>` Saves all variables, currently it is not possible to choose which variables are being saved.

####VTK
`<VTK Iterations="X" what="U,P" name="xxx"/>` Exports VTK data each X iterations, to a file with `xxx` prefix. It is possible to chose which variables are being exported. Both attributes can be omitted.

#####TXT
`<TXT Iterations="X" name="xxx" gzip="T/F"/>` Exporst data to TXT file each X iterations, to a file with `xxx` prefix,  `gzip` is a boolean(`TRUE` or `FALSE`) parameter specifying if the TXT file should be compressed.

#####Failcheck
`<Failcheck Iterations="X"/>` Checks every X iterations if NaN values are present in solution and stops simulation if any NaN is found.

#####Stop
`<Stop FluxChange="1e-5" Times="Y" Iterations="X"/>` Checks every X iterations if change of some Global value(here `Fluxchange`) is within the specified limit(here `1e-5`). If it occurs `Y` times, the simulation is stopped.

#####Sample
`<Sample Iterations="XY" what="U,P"><Point dx="10" dy="20"/></Sample>` Efficient way of sampling quantities on each iteration. `U` and `P` are quantities to be sampled, if `what` attribute is omitted all quantities are sampled. `<Point dx="10" dy="20"/>` specifies from which place will the values be taken. Sampling begins after `XY` iterations.

#####Catalyst
`<Catalyst script="vis1.py" Iterations="X" export="CellData/PointData" preprocess="T/F"/>` Runs Catalyst co-processor each X iterations using `vis1.py` Python script. Export attribute allows selecting either `CellData` or `PointData` to be exported. Preprocess is a boolean attribute(`TRUE` or `FALSE`), if active the Python script will be modified so that the files will be placed in the output directory. 

#####SaveMemoryDump

`<MemoryDump Iterations="X"/>` Saves the state of the simulation in given iteration, which allows to resume (TODO:HOW) the simulation from this exact point, with the same conditions. Warning: Created files are huge and take a long time to save.

#Example cases

##Simple case

Below is presented a simple 3-Dimensional case, with a ball in the middle of the domain. Velocity inlet is used on one side and pressure outlet on the another one(TODO:Orientacja NEWS). Notice how each dimension of the ball is specified in different way, yet it is still placed exactly in the middle of the domain:
```xml
<?xml version="1.0"?>
<CLBConfig version="2.0" output="output/test">
    <Geometry nx="128" ny="128" nz="128">
        <MRT><Box/></MRT>
        <WVelocity name="Inlet"><Box nx="1"/></WVelocity>
        <EPressure><Box dx="-1"/></EPressure>
        <Wall mask = "ALL">
            <Sphere dx="54" nx="20" dy="54" fy="74" dz="-74" nz="20"/>
        </Wall>
    </Geometry>
    <Model>
        <Params Velocity-Inlet="0.1"/>
        <Params nu="0.05"/>
    </Model>
    <VTK Iterations="100" what = "U,P"/>
    <Solve Iterations="1000"/>
</CLBConfig>
```


##Gauge

```xml
<?xml version="1.0"?>
<CLBConfig version="2.0" output="output/test">
    <Units>
        <Params Velocity="1m/s" gauge="0.1"/>
        <Params Viscosity="0.01m2/s" gauge="0.01"/>
    </Units>
    <Geometry nx="128" ny="128" nz="128">
        <MRT><Box/></MRT>
        <WVelocity name="Inlet"><Box nx="1"/></WVelocity>
        <EPressure><Box dx="-1"/></EPressure>
        <Wall mask = "ALL">
            <Sphere dx="54" nx="20" dy="54" fy="74" dz="-74" nz="20"/>
        </Wall>
    </Geometry>
    <Model>
        <Params Velocity-Inlet="1m/s"/>
        <Params nu="0.05m2/s"/>
    </Model>
    <VTK Iterations="100" what = "U,P"/>
    <Solve Iterations="1000"/>
</CLBConfig>

```
Sets units in such a way that real-world units agree with LB units. Here $1m = 1/0.1=10$, which means that each meter is equal to 10 elements in grid and $0.01[\frac{m^2}{s}]  = \frac{0.01}{0.01} = 1 => 1 Iteration[s] = \frac{1}/{10^2}$, so 1s is equal to 100 iterations. 

Notice how parameters in `<Model>` are specified and how generated case is the same as in previous example.

##Control elements

```xml
<?xml version="1.0"?>
<CLBConfig version="2.0" output="output/test">
    <Geometry nx="128" ny="128" nz="128">
        <MRT><Box/></MRT>
        <WVelocity name="Inlet"><Box nx="1"/></WVelocity>
        <EPressure><Box dx="-1"/></EPressure>
        <Wall mask = "ALL">
            <Sphere dx="54" nx="20" dy="54" fy="74" dz="-74" nz="20"/>
        </Wall>
    </Geometry>
    <Model>
        <Params Velocity-Inlet="0.1"
                nu="0.05"/>
    </Model>
    <VTK Iterations="100" what = "U,P"/>
    <Solve Iterations="1000"/>
    <Control Iterations="1000">
        <CSV file="file.csv" Time="x*1000">
        <Params Velocity="y*0.02+0.05"/>
    </CSV>
</Control>
</CLBConfig>
```
Changes `Velocity` according to the contents of `file.csv`. Here column 'x' is used to compute time and 'y' is used to calculate 'Velocity' value. Notice also that `Velocity` and `nu` parameters are given in `<Model>` container, without the need of creating separate tags for each parameter.

  defined within `Dynamics.R`.


##Synthetic Turbulence

A synthetic turbulence generator is implemented in TCLB solver. It is based on modified von Karman-Pao spectrum([Bailly and Juve, 1999](https://arc.aiaa.org/doi/10.2514/6.1999-1872)) 
```xml
<?xml version="1.0"?>
<CLBConfig version="2.0" output="output/test">
    <Units>
        <Params Velocity="1m/s" gauge="0.1"/>
        <Params Viscosity="0.01m2/s" gauge="0.01"/>
    </Units>
    <Geometry nx="128" ny="128" nz="128">
        <MRT><Box/></MRT>
        <WVelocityTurbulent name="Inlet"><Box nx="1"/></WVelocityTurbulent>
        <EPressure><Box dx="-1"/></EPressure>
        <Wall mask = "ALL">
            <Sphere dx="54" nx="20" dy="54" fy="74" dz="-74" nz="20"/>
        </Wall>
    </Geometry>
    <Model>
        <Params Velocity-Inlet="1m/s"
                nu="0.05m2/s"
                Turbulence="0.1m/s"
                MainWaveLength="10m"
                DiffusionWaveLength = "100m"/>
    </Model>
    <VTK Iterations="100" what = "U,P"/>
    <Solve Iterations="1000"/>
</CLBConfig>
```
It is important to remember that in order to use implemented turbulence generator it is required to change `WVelocity` to `WVelocityTurbulent`, e.g.: `<WVelocityTurbulent><Box nx="1"/></WVelocityTurbulent>`. The generator has more customizable attributes, given in table below, but most of them is not required for generator to work. Only the mandatory ones are provided in example above.



 Attribute | Comment 
 ------- | ------------------------------ 
 `Modes=` | Number of harmonic modes to generate for the turbulence, default '100'.
 `Spread=` | The way to divide the spectrum to a finite number of modes. Possible values: `Even`, `Log`, `Quantile`. Default is `Even`.
 `Spectrum=` | Type of spectrum to use, possible values: `Von Karman`, `One Wave`. Default is `Von Karman` 
 `MainWaveLength=` | Main wave-length in the Von Karman spectrum.
 `DiffusionWaveLength=` | Diffusion scale wave-length in the Von Karman spectrum.
 `MinWaveLength=` | Minimal space wave-length. TODO:Default value
 `MaxWaveLength=` | Maximal space wave-length.
 `TimeWaveLength=` | Time wave-length of the syntetic turbulence.
 
 It is possible to specify `WaveLength` parameters in terms of `WaveNumber` or `WaveFrequency`. 


##Symmetry

TODO:ustalić jak było z przesunięciem przy symetri, czy ma ona być na ostatnim elemencie ciała czy jedno za nim. 

##Node Types

Node type consists of several properties, which are organized in groups. Each node can have noly one property from each group. Additional groups can be



